"""Add cascade delete to education, employment, experience bulletpoints

Revision ID: 0e9d8b2ebee1
Revises: d8b96bb269c4
Create Date: 2026-01-06 01:36:03.515867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9d8b2ebee1'
down_revision: Union[str, None] = 'd8b96bb269c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'gpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.drop_constraint('education_bullet_point_education_id_fkey', 'education_bullet_point', type_='foreignkey')
    op.create_foreign_key(None, 'education_bullet_point', 'education', ['education_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employment_bullet_point_employment_id_fkey', 'employment_bullet_point', type_='foreignkey')
    op.create_foreign_key(None, 'employment_bullet_point', 'employment', ['employment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('experience_bullet_point_experience_id_fkey', 'experience_bullet_point', type_='foreignkey')
    op.create_foreign_key(None, 'experience_bullet_point', 'experience', ['experience_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experience_bullet_point', type_='foreignkey')
    op.create_foreign_key('experience_bullet_point_experience_id_fkey', 'experience_bullet_point', 'experience', ['experience_id'], ['id'])
    op.drop_constraint(None, 'employment_bullet_point', type_='foreignkey')
    op.create_foreign_key('employment_bullet_point_employment_id_fkey', 'employment_bullet_point', 'employment', ['employment_id'], ['id'])
    op.drop_constraint(None, 'education_bullet_point', type_='foreignkey')
    op.create_foreign_key('education_bullet_point_education_id_fkey', 'education_bullet_point', 'education', ['education_id'], ['id'])
    op.alter_column('education', 'gpa',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
