"""Add cascade delete to tag and link projects

Revision ID: 54fae1e77f16
Revises: 0e9d8b2ebee1
Create Date: 2026-01-06 01:52:18.264292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fae1e77f16'
down_revision: Union[str, None] = '0e9d8b2ebee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'gpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.drop_constraint('project_link_project_id_fkey', 'project_link', type_='foreignkey')
    op.create_foreign_key(None, 'project_link', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_tag_project_id_fkey', 'project_tag', type_='foreignkey')
    op.create_foreign_key(None, 'project_tag', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_tag', type_='foreignkey')
    op.create_foreign_key('project_tag_project_id_fkey', 'project_tag', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_link', type_='foreignkey')
    op.create_foreign_key('project_link_project_id_fkey', 'project_link', 'project', ['project_id'], ['id'])
    op.alter_column('education', 'gpa',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
