"""Add project, link, tag, and their corresponding cross-sectional tables

Revision ID: 8f0b7060d367
Revises: b31c219abaa0
Create Date: 2026-01-05 13:51:39.655038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0b7060d367'
down_revision: Union[str, None] = 'b31c219abaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biography_bullet_point', sa.Column('position', sa.Integer(), nullable=False))
    op.drop_column('bullet_point', 'position')
    op.alter_column('education', 'gpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('education_bullet_point', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('employment_bullet_point', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('experience_bullet_point', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience_bullet_point', 'position')
    op.drop_column('employment_bullet_point', 'position')
    op.drop_column('education_bullet_point', 'position')
    op.alter_column('education', 'gpa',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('bullet_point', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('biography_bullet_point', 'position')
    # ### end Alembic commands ###
