"""Refactored schema to include document, biography, bullet points

Revision ID: b31c219abaa0
Revises: d1dad947b68e
Create Date: 2026-01-04 22:20:24.519945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31c219abaa0'
down_revision: Union[str, None] = 'd1dad947b68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bullet_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bullet_point_pid'), 'bullet_point', ['pid'], unique=True)
    op.create_table('biography',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id')
    )
    op.create_index(op.f('ix_biography_pid'), 'biography', ['pid'], unique=True)
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id')
    )
    op.create_index(op.f('ix_document_pid'), 'document', ['pid'], unique=True)
    op.create_table('biography_bullet_point',
    sa.Column('biography_id', sa.Integer(), nullable=False),
    sa.Column('bullet_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['biography_id'], ['biography.id'], ),
    sa.ForeignKeyConstraint(['bullet_point_id'], ['bullet_point.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('biography_id', 'bullet_point_id')
    )
    op.create_table('education_bullet_point',
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.Column('bullet_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bullet_point_id'], ['bullet_point.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], ),
    sa.PrimaryKeyConstraint('education_id', 'bullet_point_id')
    )
    op.create_table('employment_bullet_point',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('bullet_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bullet_point_id'], ['bullet_point.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employment_id'], ['employment.id'], ),
    sa.PrimaryKeyConstraint('employment_id', 'bullet_point_id')
    )
    op.create_table('experience_bullet_point',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('bullet_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bullet_point_id'], ['bullet_point.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], ),
    sa.PrimaryKeyConstraint('experience_id', 'bullet_point_id')
    )
    op.alter_column('education', 'gpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.drop_column('employment', 'content')
    op.drop_column('experience', 'content')
    op.add_column('portfolio', sa.Column('first_name', sa.String(length=64), nullable=False))
    op.add_column('portfolio', sa.Column('last_name', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'last_name')
    op.drop_column('portfolio', 'first_name')
    op.add_column('experience', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('employment', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('education', 'gpa',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_table('experience_bullet_point')
    op.drop_table('employment_bullet_point')
    op.drop_table('education_bullet_point')
    op.drop_table('biography_bullet_point')
    op.drop_index(op.f('ix_document_pid'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_biography_pid'), table_name='biography')
    op.drop_table('biography')
    op.drop_index(op.f('ix_bullet_point_pid'), table_name='bullet_point')
    op.drop_table('bullet_point')
    # ### end Alembic commands ###
