"""Add PID and position(Employment) columns

Revision ID: d1dad947b68e
Revises: 52ca248f1323
Create Date: 2025-12-30 15:48:08.883231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1dad947b68e'
down_revision: Union[str, None] = '52ca248f1323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('pid', sa.UUID(), nullable=False))
    op.alter_column('education', 'gpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('education', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_education_pid'), 'education', ['pid'], unique=True)
    op.add_column('employment', sa.Column('pid', sa.UUID(), nullable=False))
    op.add_column('employment', sa.Column('position', sa.String(length=64), nullable=False))
    op.alter_column('employment', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_employment_pid'), 'employment', ['pid'], unique=True)
    op.add_column('experience', sa.Column('pid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_experience_pid'), 'experience', ['pid'], unique=True)
    op.add_column('portfolio', sa.Column('pid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_portfolio_pid'), 'portfolio', ['pid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_pid'), table_name='portfolio')
    op.drop_column('portfolio', 'pid')
    op.drop_index(op.f('ix_experience_pid'), table_name='experience')
    op.drop_column('experience', 'pid')
    op.drop_index(op.f('ix_employment_pid'), table_name='employment')
    op.alter_column('employment', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('employment', 'position')
    op.drop_column('employment', 'pid')
    op.drop_index(op.f('ix_education_pid'), table_name='education')
    op.alter_column('education', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('education', 'gpa',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('education', 'pid')
    # ### end Alembic commands ###
