"""Add cascade delete to biography bullet points

Revision ID: d8b96bb269c4
Revises: 6d8f8832381c
Create Date: 2026-01-05 20:01:11.307163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b96bb269c4'
down_revision: Union[str, None] = '6d8f8832381c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('biography_bullet_point_biography_id_fkey', 'biography_bullet_point', type_='foreignkey')
    op.create_foreign_key(None, 'biography_bullet_point', 'biography', ['biography_id'], ['id'], ondelete='CASCADE')
    op.alter_column('education', 'gpa',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'gpa',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'biography_bullet_point', type_='foreignkey')
    op.create_foreign_key('biography_bullet_point_biography_id_fkey', 'biography_bullet_point', 'biography', ['biography_id'], ['id'])
    # ### end Alembic commands ###
