"""add employment, education, experience. updated portfolio

Revision ID: f49e981d1324
Revises: 0e08245b9de0
Create Date: 2025-12-24 16:16:55.125387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49e981d1324'
down_revision: Union[str, None] = '0e08245b9de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='portfolio_pkey'),
    sa.UniqueConstraint('email', name='portfolio_email_key')
    )
    # ### end Alembic commands ###
